### ISSUE TITLE
Question about data structure

### ISSUE THREAD

**Issue by eirini-zormpa** [OttaviaE/implicitMeasures#3]
I have never used IAT measures, so this may be a naive question!

The `clean_IAT()` function seems to me to require a fairly rigid data structure to work. Would this function be easy to use with a different dataset? That is, are data from IAT experiments typically already in that structure or do they require any preprocessing? If they do require preprocessing, I think it would be helpful to include more information on how users need to prepare their data before using this function.

#openjournals/joss-reviews#2297

**Comment by OttaviaE** [comment]
Actually, the point of the clean_iat() function(as well as the clean_iat() function) is to be as flexible as possible. IAT data are usaully collected by using the sofatware Inquisit, whie results in a data set simialr to that used as an example. Anyways, regardless of the specific software used for the administration, the IAT usually results in a dataset with respondents IDs, their RTs, their accuracy responses, and the lables of the critical blocks. Once the users have this infromation, they can use the function with no further problems, by just using the specific lables for each arument. To answer your question, users should not be reuqired to do any preprocessing for using the function that is supposed to to all the preprocessing work for them.

**Comment by eirini-zormpa** [comment]
awesome thank you!

**Comment by OttaviaE** [comment]
Thanks! If you have any further inquiries, please do not hesitate to contact me!
